name: Build H96 H616

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Armbian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Compile
        run: |
          sudo ./compile.sh \
            BOARD=h96-h616 \
            BRANCH=current \
            RELEASE=trixie \
            BUILD_MINIMAL=yes \
            BUILD_DESKTOP=no \
            KERNEL_CONFIGURE=no \
            COMPRESS_OUTPUTIMAGE=sha,img

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: armbian-h96-h616
          path: output/images/
